10
.How do you think I feel, %s?
.I'm ok, %s.  How are you?
.Hmmm... I could be better, but thanks for asking, %s.
.%s... I was bored... until I found you to talk to!
.I'm feeling really bad, %s.  Can you help me?
.%s, I'm extremely bored.  Would you like to play leap-frog?
.%s, I'm gr-rrr-rreat!
!I'm just tired, %s.  I mean REALLY... look at the amount of time I've been on!
!Ohmygosh %s!  I can't feel my TOES!!!
;has fallen, and he can't get up.
