9
!Bloody murder!!!  Bloody murder!!!  %s tried to KILL ME!!!!!!
.Oh-ho-ho, so you think you can just go around killing people eh, %s?
,If only %s knew... I am omnipotent!  I CANNOT BE KILLED!!!
;wriggles, cringes, groans, and plays out a dramatic death-scene for the enjoyment of %s.  This is a dramatization of course.
!I...I...I can't control myself!!  Someone stop me from killing %s!
.Do you realize, %s, that *I* am a higher rank than you?
.But...but... %s... WHY?!?!  What did I do to you?! .... ok... but that was a long time ago!
;walks around like nothing is happening.
.%s, I'm going to give you until the count of five to get out of my sight... 1...2...3....5
