11
;takes %s's punches and delivers his own blows in return.
,Why do you do this to me, %s?
!%s is very violent.... yes... very violent indeed!
.Oh!  Oh!  You wanna fight?!.. Huh, %s?  Do ya?!
.%s, don't even try me.  I could take you one-handed.
!You wanna get hit?  %s??
;slaps %s!
;backhands %s!
;punches %s in the gut!
;punches %s in the face!
!%s... Don't *even* think about it, you wimp.
