16
.Just who do you think you're grinin' at, %s?!
;winks at %s.
.Wipe that smile off your face, %s!
.Just happy to see me, eh %s?
;smiles in %s's general direction.
;flinches, then half-smiles at %s.
;hands %s a toothbrush.
!Gee, %s, I didn't know you cared!
.Well, why didn't you just say so, %s?!
,Playing 'hard-to-get' eh?  Two can play at that, %s.
;smiles at %s.
;poses and hopes %s takes a picture.
;smiles... "Are you happy now, %s?"
;has no teeth, %s.
,All %s ever wants... do this, do that.
;smiles happily at %s... or is it a smirk?
