13
.What would you like me to say, %s?
!I have a spork, %s.  Do you?  I didn't think so.
!Wow!!  %s is actually talking to me!!!
.No comment, %s.
,Why does %s aks me?  I have nothing to say.
.How are you today, %s?  Good I hope?
,Why do you always pick on me?!  Huh, %s?!  Why?!
!I don't have to do what you say, %s.  So *there*.
.%s can't make me... Nah-na nah-na nah..naaaaah.
;does his best James Dean impression.
.%s, who are you to tell me what to do?!
;speaks to everyone but %s.
;burys his head in his hands....  "No!!!  I don't wanna!"
